<?php

require_once( get_template_directory() . '/includes/acf/torque-acf-search-class.php' );

class Waterside_ACF {

  public function __construct() {
    add_action('admin_init', array( $this, 'acf_admin_init'), 99);
    add_action('acf/init', array( $this, 'acf_init' ) );

    // hide acf in admin - client doesnt need to see this
    // add_filter('acf/settings/show_admin', '__return_false');

    // add acf fields to wp search
    if ( class_exists( 'Torque_ACF_Search' ) ) {
      add_filter( Torque_ACF_Search::$ACF_SEARCHABLE_FIELDS_FILTER_HANDLE, array( $this, 'add_fields_to_search' ) );
    }
  }

  public function acf_admin_init() {
    // hide options page
    // remove_menu_page('acf-options');
  }

  public function add_fields_to_search( $fields ) {
    // $fields[] = 'custom_field_name';
    return $fields;
  }

  public function acf_init() {
    // start content sections

    if( function_exists('acf_add_local_field_group') ):

      acf_add_local_field_group(array(
        'key' => 'group_5ede111016767',
        'title' => 'Page Hero',
        'fields' => array(
          array(
            'key' => 'field_5ede11a94cf15',
            'label' => 'Enable Hero?',
            'name' => 'enable_hero',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_5ede11cf4cf16',
            'label' => 'Media',
            'name' => 'media',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11a94cf15',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'image' => 'Image',
              'video-external' => 'Video (Vimeo)',
              'video-internal' => 'Video (Internal)',
            ),
            'default_value' => array(
              0 => 'image',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5ee015b67a17f',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => 'Override the page title by entering text into this field.',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11a94cf15',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ede11fb4cf17',
            'label' => 'Image',
            'name' => 'image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11cf4cf16',
                  'operator' => '==',
                  'value' => 'image',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5ede12284cf18',
            'label' => 'Video (Vimeo)',
            'name' => 'video_external',
            'type' => 'url',
            'instructions' => 'Do not use the embed code. Simply copy the Vimeo video URL directly from the browser\'s URL bar, and paste into the field provided.',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11cf4cf16',
                  'operator' => '==',
                  'value' => 'video-external',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'E.g: https://vimeo.com/395979637',
          ),
          array(
            'key' => 'field_5ede13054cf19',
            'label' => 'Video (Internal)',
            'name' => 'video_internal',
            'type' => 'file',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11cf4cf16',
                  'operator' => '==',
                  'value' => 'video-internal',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4',
          ),
          array(
            'key' => 'field_5ededf76deda6',
            'label' => 'Hero Mask',
            'name' => 'hero_mask',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11a94cf15',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
          ),
          array(
            'key' => 'field_5edee25cd7f5e',
            'label' => 'Hero Mask Opacity',
            'name' => 'hero_mask_opacity',
            'type' => 'range',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11a94cf15',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '0.50',
            'min' => '',
            'max' => 1,
            'step' => '0.05',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_5ede14dfece0e',
            'label' => 'Autoplay Video?',
            'name' => 'autoplay_video',
            'type' => 'true_false',
            'instructions' => 'Attempt to autoplay the video. Note that due to browser restrictions this option will mute the video.',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11cf4cf16',
                  'operator' => '==',
                  'value' => 'video-external',
                ),
              ),
              array(
                array(
                  'field' => 'field_5ede11cf4cf16',
                  'operator' => '==',
                  'value' => 'video-internal',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_5ede1454ece0d',
            'label' => 'Loop Video?',
            'name' => 'loop_video',
            'type' => 'true_false',
            'instructions' => 'Attempt to loop the video',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5ede11cf4cf16',
                  'operator' => '==',
                  'value' => 'video-external',
                ),
              ),
              array(
                array(
                  'field' => 'field_5ede11cf4cf16',
                  'operator' => '==',
                  'value' => 'video-internal',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));

      acf_add_local_field_group(array(
        'key' => 'group_5ed86b836b714',
        'title' => 'Waterside Options',
        'fields' => array(
          array(
            'key' => 'field_5ed86b890c78e',
            'label' => 'Contact Info',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5ed86bf20c78f',
            'label' => 'Address',
            'name' => 'address',
            'type' => 'text',
            'instructions' => 'Use the &lt;br&gt; tag to insert a line-break.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ed86c0b0c790',
            'label' => 'Phone',
            'name' => 'phone',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ed86c110c791',
            'label' => 'Email',
            'name' => 'email',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ed8799b14a6f',
            'label' => 'Footer',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5edec0ebe470e',
            'label' => 'CTA',
            'name' => 'footer_cta',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_5ed879b614a70',
            'label' => 'Alternate Logo',
            'name' => 'alternate_logo',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5ee04b3347043',
            'label' => 'Alternate Logo Link',
            'name' => 'alternate_logo_link',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5ed87b047c796',
            'label' => 'Social Media',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5ed87b217c797',
            'label' => 'Social Channels',
            'name' => 'social_channels',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'collapsed' => '',
            'sub_fields' => array(
              array(
                'key' => 'field_5ed87b3a38394',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_5ed87b6138395',
                'label' => 'URL',
                'name' => 'url',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '60',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
          ),
          array(
            'key' => 'field_5ee19c4ba1586',
            'label' => 'Floorplans',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5ee19c5ea1587',
            'label' => 'All Floorplans File',
            'name' => 'all_floorplans_file',
            'type' => 'file',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5ee2b9419b963',
            'label' => 'Other',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5ee2b95e9b964',
            'label' => 'Google Maps API Key',
            'name' => 'google_maps_api_key',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'options_page',
              'operator' => '==',
              'value' => 'acf-options',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));

      acf_add_local_field_group(array(
	'key' => 'group_5edde2f4c53e3',
	'title' => 'Content Modules',
	'fields' => array(
		array(
			'key' => 'field_5edde316fa054',
			'label' => 'Content Modules',
			'name' => 'content_modules',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5ee00e90724ed' => array(
					'key' => 'layout_5ee00e90724ed',
					'name' => 'content_spacer',
					'label' => 'Content Spacer',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ee00e99724ee',
							'label' => 'Spacer Height',
							'name' => 'spacer_height',
							'type' => 'number',
							'instructions' => 'Enter only a number, either negative or positive.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 3,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5ee00f32724ef',
							'label' => 'Spacer Measurement',
							'name' => 'spacer_measurement',
							'type' => 'select',
							'instructions' => 'Select measurement used to calculate spacer height.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'px' => 'Pixels (px)',
								'vw' => 'Percentage of viewport width (vw)',
								'vh' => 'Percentage of viewport height (vh)',
							),
							'default_value' => array(
								0 => 'vw',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5ee00f98724f0',
							'label' => 'Visibility',
							'name' => 'visibility',
							'type' => 'select',
							'instructions' => 'Choose which devices you\'d like to display the spacer on.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'all_devices' => 'All Devices',
								'mobile_only' => 'Mobile Only',
								'tablet_only' => 'Tablet Only',
								'desktop_only' => 'Desktop Only',
								'mobile_tablet' => 'Mobile & Tablet',
								'tablet_desktop' => 'Tablet & Desktop',
							),
							'default_value' => array(
								0 => 'all_devices',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5edde31c428fd' => array(
					'key' => '5edde31c428fd',
					'name' => 'image_title_text_cta',
					'label' => 'Image, Title, Text & CTA',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5edde5804a501',
							'label' => 'Alignment',
							'name' => 'alignment',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'align-image-left' => 'Image left, content right',
								'align-image-right' => 'Content left, image right',
							),
							'default_value' => array(
								0 => 'align-image-left',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5edde466d7631',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5edde498d7632',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5edde4a6d7633',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5edde4d9d7634',
							'label' => 'CTA',
							'name' => 'cta',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5edef7cf22dfb' => array(
					'key' => 'layout_5edef7cf22dfb',
					'name' => 'cta_banner',
					'label' => 'CTA Banner',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5edef7d622dfc',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5edef7dc22dfd',
							'label' => 'CTA',
							'name' => 'cta',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5ee0043b724ec' => array(
					'key' => 'layout_5ee0043b724ec',
					'name' => 'title_text',
					'label' => 'Title & Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ee070bf211f7',
							'label' => 'Column Arrangement',
							'name' => 'column_arrangement',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'one' => 'One Column',
								'two' => 'Two Columns',
							),
							'default_value' => array(
								0 => 'one',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5ee0729dae084',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'light-grey' => 'Light Grey',
								'medium-grey' => 'Medium Grey',
								'dark-grey' => 'Dark Grey',
							),
							'default_value' => array(
								0 => 'medium-grey',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5ee0147a0ebf4',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ee0176d1da60',
							'label' => 'Title Color',
							'name' => 'title_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'white' => 'White',
								'teal' => 'Teal',
							),
							'default_value' => array(
								0 => 'white',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5ee0148b0ebf5',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ee070bf211f7',
										'operator' => '==',
										'value' => 'one',
									),
								),
							),
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5ee070fd211f8',
							'label' => 'Column One Text',
							'name' => 'column_one_text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ee070bf211f7',
										'operator' => '==',
										'value' => 'two',
									),
								),
							),
							'wrapper' => array(
								'width' => '49.5',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5ee0710e211f9',
							'label' => 'Column Two Text',
							'name' => 'column_two_text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ee070bf211f7',
										'operator' => '==',
										'value' => 'two',
									),
								),
							),
							'wrapper' => array(
								'width' => '49.5',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5ee053ddae667' => array(
					'key' => 'layout_5ee053ddae667',
					'name' => 'single_media',
					'label' => 'Single Media',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ee053e7ae668',
							'label' => 'Media',
							'name' => 'media',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'image' => 'Image',
								'video-external' => 'Video (Vimeo)',
								'video-internal' => 'Video (Internal)',
							),
							'default_value' => array(
								0 => 'image',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5ee0540dae669',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ee053e7ae668',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5ee0542cae66a',
							'label' => 'Video (Vimeo)',
							'name' => 'video_external',
							'type' => 'url',
							'instructions' => 'Do not use the embed code. Simply copy the Vimeo video URL directly from the browser\'s URL bar, and paste into the field provided.',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ee053e7ae668',
										'operator' => '==',
										'value' => 'video-external',
									),
								),
							),
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'E.g: https://vimeo.com/395979637',
						),
						array(
							'key' => 'field_5ee0545cae66b',
							'label' => 'Video (Internal)',
							'name' => 'video_internal',
							'type' => 'file',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ee053e7ae668',
										'operator' => '==',
										'value' => 'video-internal',
									),
								),
							),
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'mp4',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5ee0784c61b7c' => array(
					'key' => 'layout_5ee0784c61b7c',
					'name' => 'floorplans',
					'label' => 'Floorplans',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_5ee0786d61b7d' => array(
					'key' => 'layout_5ee0786d61b7d',
					'name' => 'map',
					'label' => 'Map',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ee1b888c11ef',
							'label' => 'Map',
							'name' => 'map',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'torque_map',
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'id',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c869eb43ec10' => array(
					'key' => 'layout_5c869eb43ec10',
					'name' => 'gallery_grid',
					'label' => 'Gallery Grid',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c869ee83ec12',
							'label' => 'Grid Rows',
							'name' => 'grid_rows',
							'type' => 'range',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1,
							'min' => 1,
							'max' => 2,
							'step' => 1,
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_5c869fef3ec13',
							'label' => 'Images',
							'name' => 'images',
							'type' => 'repeater',
							'instructions' => 'Picture a grid with 12 columns and 2 rows. </br>The grid lines between the columns (including the first and last one) can be labelled from 0 to 13, and between the rows from 0 to 2. </br>For each image, you can define the area in this grid that it will live in (on desktop) by giving it a column line start/finish and a row line start/finish. </br></br> The order you add the images will have no effect on desktop (since we\'re just giving it a grid area), but will be relevant for mobile and tablet.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5c869ffc3ec14',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Image',
							'sub_fields' => array(
								array(
									'key' => 'field_5c869ffc3ec14',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5c86a00f3ec15',
									'label' => 'Column Start',
									'name' => 'column_start',
									'type' => 'range',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => 0,
									'max' => 11,
									'step' => 1,
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_5c86a0573ec16',
									'label' => 'Column End',
									'name' => 'column_end',
									'type' => 'range',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => 1,
									'max' => 12,
									'step' => 1,
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_5c86a0693ec17',
									'label' => 'Row Start',
									'name' => 'row_start',
									'type' => 'range',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => 0,
									'max' => 1,
									'step' => 1,
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_5c86a07f3ec18',
									'label' => 'Row End',
									'name' => 'row_end',
									'type' => 'range',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => 1,
									'max' => 2,
									'step' => 1,
									'prepend' => '',
									'append' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5e3ad9d558b9d' => array(
					'key' => 'layout_5e3ad9d558b9d',
					'name' => 'contact_form',
					'label' => 'Contact Form',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e3ada3658b9f',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => 'wpautop',
						),
						array(
							'key' => 'field_5e3c8ab0ea919',
							'label' => 'Form Options',
							'name' => 'form_options',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'sub_fields' => array(
								array(
									'key' => 'field_5e3c8d67ea91a',
									'label' => 'Email Notification Subject',
									'name' => 'email_notification_subject',
									'type' => 'text',
									'instructions' => 'Subject of the email notification.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5e3c8d81ea91b',
									'label' => 'Send Notification To',
									'name' => 'send_notification_to',
									'type' => 'email',
									'instructions' => 'If blank this will default to the site administrator\'s email address.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_5e3c90ffea91c',
									'label' => 'Submit Button Text',
									'name' => 'submit_button_text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '40',
										'class' => '',
										'id' => '',
									),
									'default_value' => 'Submit',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5e3c96dc8402e',
									'label' => 'Hide Labels?',
									'name' => 'hide_labels',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5e3c96f78402f',
									'label' => 'Use Labels as Placeholders?',
									'name' => 'use_labels_as_placeholders',
									'type' => 'true_false',
									'instructions' => 'Where possible, use the label as a placeholder.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 1,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5e3d7c91a9275',
									'label' => 'Redirect After Submission?',
									'name' => 'redirect_after_submission',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
								),
							),
						),
						array(
							'key' => 'field_5e3c84cf147ba',
							'label' => 'Form Fields',
							'name' => 'form_fields',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5e3c85118224b',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5e3c85f73e60e',
									'label' => 'Type',
									'name' => 'type',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'text' => 'Text',
										'name' => 'Name',
										'email' => 'Email',
										'phone' => 'Phone',
										'url' => 'Website',
										'textarea' => 'Textarea',
										'checkbox' => 'Checkbox',
										'checkbox-multiple' => 'Checkbox Group',
										'radio' => 'Radio',
										'select' => 'Select',
										'date' => 'Date',
									),
									'default_value' => array(
										0 => 'text',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 1,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5e3c85118224b',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5e3c89650d274',
									'label' => 'Width',
									'name' => 'width',
									'type' => 'range',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => 100,
									'min' => 25,
									'max' => 100,
									'step' => 25,
									'prepend' => '',
									'append' => '%',
								),
								array(
									'key' => 'field_5e3c89bc0d275',
									'label' => 'Required?',
									'name' => 'required',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5e3caaa348c06',
									'label' => 'Input Options',
									'name' => 'input_options',
									'type' => 'repeater',
									'instructions' => 'List the options available for the input field.',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5e3c85f73e60e',
												'operator' => '==',
												'value' => 'checkbox-multiple',
											),
										),
										array(
											array(
												'field' => 'field_5e3c85f73e60e',
												'operator' => '==',
												'value' => 'radio',
											),
										),
										array(
											array(
												'field' => 'field_5e3c85f73e60e',
												'operator' => '==',
												'value' => 'select',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 1,
									'max' => 0,
									'layout' => 'row',
									'button_label' => 'Add Option',
									'sub_fields' => array(
										array(
											'key' => 'field_5e3caab648c07',
											'label' => 'Option Label',
											'name' => 'option_label',
											'type' => 'text',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
									),
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5fe0a898b1db1' => array(
					'key' => 'layout_5fe0a898b1db1',
					'name' => 'wysiwyg',
					'label' => 'WYSIWYG',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fe0a8abb1db2',
							'label' => 'content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Content Module',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

      endif;

    // start content sections
  }
}

?>
